/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import code.readcsv;
import data.loadData;
import db.db;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author anom
 */
public class BtloadData extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loadData.class.getName());

    /**
     * Creates new form loadData
     */
    public BtloadData() {
        initComponents();
    }
    
    private List<readcsv> loadedData;

    private void loadCSV() {

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == fileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = loadData.Loadcsv(selectedFile);
            //System.out.println("Size" + loadedData.size());
            displayDataInTable(loadedData);
        }
    }

    private void displayDataInTable(List<readcsv> dataList) {

        DefaultTableModel model = (DefaultTableModel) tblLoadData.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++) {
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getC_id(),
                row.getP_id(),
                row.getP_name(),
                row.getQuantity(),
                row.getP_unit(),
                row.getDate(),
                row.getPrice(),
                row.getRegion()
            });
        }
    }

    public void saveData() {
        try {
            Connection con = db.getConnection();
            con.setAutoCommit(false);
            String query = "INSERT INTO sales (transaction_id, customer_id, product_id, product_name, quantity, priceper_unit, date, total_price, region) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);

            DefaultTableModel model = (DefaultTableModel) tblLoadData.getModel();
            double total = 0;

            for (int i = 0; i < model.getRowCount(); i++) {
                int tra_id = Integer.parseInt(model.getValueAt(i, 0).toString());
                int c_id = Integer.parseInt(model.getValueAt(i, 1).toString());
                int p_id = Integer.parseInt(model.getValueAt(i, 2).toString());
                String p_name = model.getValueAt(i, 3).toString();
                int quantity = Integer.parseInt(model.getValueAt(i, 4).toString());
                double p_unit = Double.parseDouble(model.getValueAt(i, 5).toString());
                String date = model.getValueAt(i, 6).toString();
                double price = Double.parseDouble(model.getValueAt(i, 7).toString());
                String region = model.getValueAt(i, 8).toString();

                total += price;

                pst.setInt(1, tra_id);
                pst.setInt(2, c_id);
                pst.setInt(3, p_id);
                pst.setString(4, p_name);
                pst.setInt(5, quantity);
                pst.setDouble(6, p_unit);
                pst.setString(7, date);
                pst.setDouble(8, price);
                pst.setString(9, region);

                pst.addBatch();
            }

            pst.executeBatch();
            con.commit();

            JOptionPane.showMessageDialog(null, "Data saved successfully!");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoadData = new javax.swing.JTable();
        topPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnLoadData = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(940, 700));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.BorderLayout());

        tablePanel.setLayout(new java.awt.BorderLayout());

        tblLoadData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Customer ID", "Product ID", "Product Name", "Quantity", "Priceper Unit", "Date", "Total Price", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLoadData);
        if (tblLoadData.getColumnModel().getColumnCount() > 0) {
            tblLoadData.getColumnModel().getColumn(0).setResizable(false);
            tblLoadData.getColumnModel().getColumn(1).setResizable(false);
            tblLoadData.getColumnModel().getColumn(2).setResizable(false);
            tblLoadData.getColumnModel().getColumn(3).setResizable(false);
            tblLoadData.getColumnModel().getColumn(4).setResizable(false);
            tblLoadData.getColumnModel().getColumn(6).setResizable(false);
            tblLoadData.getColumnModel().getColumn(8).setResizable(false);
        }

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(tablePanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(centerPanel, java.awt.BorderLayout.CENTER);

        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(15, 23, 42));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 231, 235));
        jLabel1.setText("Data Load");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        topPanel.add(jPanel3);

        buttonPanel.setBackground(new java.awt.Color(102, 102, 102));

        btnLoadData.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnLoadData.setText("Load Data");
        btnLoadData.addActionListener(this::btnLoadDataActionPerformed);

        btnSave.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnPrint.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/load.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        topPanel.add(buttonPanel);

        jPanel1.add(topPanel, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDataActionPerformed
        // TODO add your handling code here:
        
        loadCSV(); // calling the method to load the csv file
        
    }//GEN-LAST:event_btnLoadDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        saveData();  // calling the save data mothod to save data
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        
        try {
            boolean complete = tblLoadData.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Datas"), new MessageFormat("Page {0}"));
            
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e){
            JOptionPane.showMessageDialog(null, 0);
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadData;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable tblLoadData;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
